CMakeLists.txt
build.py
conformance_tests/test_conformance.cpp
unit_tests/test_parse_format_spec.cpp

Small fixes:
- Disable the `poison-system-directories` warning; something in CppUTest triggers it but we're not cross-compiling and it's only for the test harness stuff, so just shut it up.
- Emit a compilation database for editors / tools that enjoy it.
- Explicit test for left-justified field-width strings (e.g. `%-10s`), there was a user report but I couldn't repo. Nice to have tests either way.

Poison System Directories

---

.github/workflows/presubmit.yml

This PR just moves the CI over to the new ghcr.io GitHub Container Registry and uses the new dynamic `GITHUB_TOKEN` auth token. This way I can delete the PAT that impersonates me every time we build, should also help with CI for any pull requests that come in.

Use GitHub Container Registry and `GITHUB_TOKEN`

---

README.md

Paland's printf is quite popular in the embedded world. I just added his last name so that: 1) it's clearer what "printf" the README is referring to; 2) it's more googleable (e.g., when someone searches for "tinyprintf vs Paland printf")

README: "Paland's printf" instead of "printf"

---

CMakeLists.txt
nanoprintf.h

Reasonable compilation settings were giving "unhandled case in switch" warnings. This PR silences the warnings and fixes the build config that was letting it through.

add -Wswitch-enum and tidy up

---

nanoprintf.h

- slightly shorter switch-case code, seeing if it helps codegen
- gcc fallthrough comments
- silence the implicit fallthrough warning
- inc vs =1, just noodling around now
- remove a redundant parse loop

Code size golfing

---

nanoprintf.h

Our platform is an odd 24 bits - so this bug was discovered.

fix fractional floating point values on platforms where unsigned < 64 bits

---

LICENSE
nanoprintf.h
tests/conformance.cc
tests/doctest_main.cc
tests/unit_nanoprintf.h

1. Support MSVC 17, which doesn't compile its own STL cleanly at /Wall
2. Update the license file to explicitly exclude the doctest.h amalgamation from the 0bsd/unlicense; it's MIT.
3. Tiny little cleanup; 1-character format strings `%` and `c` didn't need to load/inc/store cbuf_len, just store `1`.

New MSVC support, license update, tiny simplification

---

CONTRIBUTORS.md
nanoprintf.h

On platforms that have a 16-bit `unsigned int`, the `implicit_one` constant is mis-calculated. Explicitly casting this to a `uint32_t` fixes the issue.
Running tests via `./b` has all test passing.

Issue #246. Fixes formatting floats via gcc-avr.

---

CONTRIBUTORS.md
nanoprintf.h
tests/unit_vpprintf.cc

Hey there,
First of all thanks for nanoprintf - it's been a great addition to a few of my projects.
I came across an issue (or rather unexpected behaviour) when using it in my kernel, specifically when formatting a string as `%.*s` and passing 0 as the precision. As expected this will write 0 characters, but the pointer for the string content is still de-referenced in the loop condition (to check for a null terminator). This is fine if the pointer for the string content is valid, but if the pointer is null it results in null deref.
It might sound silly wanting to write a string with a precision of 0 and null for the data, but my use case is printing human-readable debug data passed from a device driver (where strings are represented with a data pointer + length). In this case a driver …

Fix for accessing string content when precision is 0.

---

CONTRIBUTORS.md
README.md
nanoprintf.h
tests/unit_fsplit_abs.cc
tests/unit_ftoa_rev.cc

The impact on footprint and performance is tiny and the code turned out to be relatively simple. In my opinion a mathematical correctness is definitely worth for such a minor sacrifice.

Introduce rounding

---

README.md
nanoprintf.h

This one reduces the number of assignment operations and does comparisons against `NPF_FMT_SPEC_OPT_NONE`, which equals zero. On AVR and PIC32 it manages to decrease the binary size by a whopping 96 and 128 bytes respectively. Though even more surprisingly it also somehow manages to increase the binary size by 16 bytes on my Cortex-M7 build.

Optimize format specifier parsing

---

nanoprintf.h

Instead of checking if the respective flags are defined, we need to check if the flag is 1. They are always defined. The code compiles on compilers that don't have __builtin_clzll now.

Check for Clang / GCC works now.

---

nanoprintf.h

Hey again!
The issue is that when using large format specifiers nanoprintf makes use of `ssize_t`, and on non-msvc compilers that means including <sys/types.h>. This header isn't freestanding (as per the C spec), and so its existence can't be relied upon - and it often results in a compilation failure for freestanding projects. So apparently I'd patched around this in my kernel project a long time ago and forgotten, but it popped up recently when getting someone else setup with nanoprintf. So here I am opening a PR haha.
This PR is my proposed solution, but let me know what you think. I imagine if you were to merge this you'd want this documented in the readme as well - I'm also happy to do that :)
This isn't addressed here, but the other issue with compiling nanoprintf as freestanding …

Freestanding improvements (ssize_t definition and inttypes.h usage)

---

nanoprintf.h
tests/conformance.cc

Fixes the float formatting issue discovered by @josesimoes in #273.
Example of failing code:
```C
npf_snprintf(..., ..., "%.5g", (double)INFINITY);
```
Output: `00inf`

Fix precision padding for float specifiers

---

nanoprintf.h

The `field_width` member of the format spec structure was only being initialized in a code path where it was known to be used in the future. This confuses GCC's always-flaky `maybe-uninitialized` warning logic, which is disabled in `nanoprintf.h` but seems to persist due to a GCC bug where LTO ignores warning flags.
So, this PR just moves `field_width` initialization to the common path.

hoist field width initialization to avoid LTO warning

---

.github/workflows/presubmit.yml
nanoprintf.h

This PR re-slices the linux CI build from the top-level clang/gcc pivot to a new x64/arm64 runner pivot. arm64 uses the new stock github runners, and x64 still uses my bleeding-edge weekly docker build. 
I confirmed that this catches the bug that @kingiler reported about arm64 gcc using unsigned char by default, which they fixed in https://github.com/charlesnicholson/nanoprintf/pull/280.

CI: arm64 linux

---

nanoprintf.h
tests/unit_snprintf.cc

This PR skips null %s parameters- it doesn't dereference them and instead prints nothing.

don't print null %s values

---

CMakeLists.txt

Just tidying up, no functionality changes

cmake: don't use &&, use multiple COMMAND elements

---

nanoprintf.h
tests/unit_parse_format_spec.cc
tests/unit_vpprintf.cc

It's undefined by the spec but less surprising this way, and less code. This PR is a reimplementation of https://github.com/charlesnicholson/nanoprintf/pull/292 by @stefano-zanotti-88 with some test fixup.

Honor field-width / precision for %c and %s

---

nanoprintf.h

As suggested by @stefano-zanotti-88, there's no size impact and this approach is much better. (I don't reach for gotos even when they're appropriate; using them improves this code)

Internal cleanup, use gotos instead of if guards
